# Generated by Django 2.2.3 on 2019-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampleTable',
            fields=[
                ('parking_slotname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('parking_floor', models.IntegerField()),
                ('parking_nearest', models.CharField(default='north', max_length=30)),
            ],
            options={
                'db_table': 'Parking',
            },
        ),
    ]
